---
- hosts: localhost
  vars:
    ansible_collection_root: /home/{{ansible_user_id}}/src/ansible_collections
    waveserver5:
      modules:
        - system
    overwrite: true
  tasks:
    - name: run execution
      include_tasks: playbook_tasks.yml
      vars:
        product: waveserver5
      with_items: "{{ waveserver5.modules }}"
