---
- hosts: localhost
  vars:
    ansible_collection_root: /home/{{ansible_user_id}}/src/ansible_collections
    saos10:
      modules:
        - classifiers
        - fds
        - fps
    overwrite: true
  tasks:
    - name: run execution
      include_tasks: playbook_tasks.yml
      vars:
        product: saos10
      with_items: "{{ saos10.modules }}"
