---
- hosts: localhost
  vars:
    ansible_collection_root: /home/{{ansible_user_id}}/src/ansible_collections
    waveserver5:
      modules:
        - classifiers
    overwrite: true
  tasks:
    - name: remove waveserver5 directory
      ansible.builtin.file:
        path: build/waveserver5
        state: absent
    - name: run execution
      include_tasks: playbook_tasks.yml
      with_items: "{{ waveserver5.modules }}"
    - name: Run black
      ansible.builtin.command: black .
      args:
        chdir: "{{ ansible_collection_root }}/ciena/waveserver5/plugins"
    - name: Run doc gen
      ansible.builtin.command: collection_prep_add_docs -b master -p .
      args:
        chdir: "{{ ansible_collection_root }}/ciena/waveserver5"
