---
# ansible-playbook generate_waveserver5.yml -e modules=system
- hosts: localhost
  vars:
    ansible_collection_root: /home/{{ansible_user_id}}/src/ansible_collections
    modules:
      - system
      - xcvrs
      - ptps
      - ports
      - pm
    overwrite: true
  tasks:
    - name: Remove directory
      ansible.builtin.file:
        path: build/waveserver5
        state: absent
    - name: Run execution
      include_tasks: playbook_tasks.yml
      vars:
        product: waveserver5
      with_items: "{{ modules }}"
