---
- hosts: localhost
  vars:
    saos10:
      location: /home/jgroom/src/ansible_collections/ciena/saos10
      modules:
        - classifiers
        - fds
    overwrite: true
  tasks:
    - name: remove saos10 directory
      ansible.builtin.file:
        path: build/saos10
        state: absent
    - name: run execution
      include_tasks: playbook_tasks.yml
      with_items: "{{ saos10.modules }}"
    - name: Run black
      ansible.builtin.command: black .
      args:
        chdir: "{{ saos10.location }}/plugins"
    - name: Run doc gen
      ansible.builtin.command: collection_prep_add_docs -b master -p .
      args:
        chdir: "{{ saos10.location }}"
