---
- name: remove directory
  ansible.builtin.file:
    path: build/{{ product }}
    state: absent
- name: Init Generation
  include_role:
    name: init
  vars:
    structure: collection
    rm_dest: build/{{ product }}
    collection_org: ciena
    collection_name: '{{ product }}'
    model: models/{{ product }}/{{ item }}/{{ product }}_{{ item }}.yml
    transport: netconf
- name: Generation
  include_role:
    name: scaffold_rm_facts
  vars:
    structure: collection
    rm_dest: build/{{ product }}
    collection_org: ciena
    collection_name: '{{ product }}'
    model: models/{{ product }}/{{ item }}/{{ product }}_{{ item }}.yml
    transport: netconf
- name: Copy modules
  block:
    - name: Copy modules
      ansible.builtin.copy:
        src: build/{{ product }}/plugins/modules/{{ product }}_{{ item }}.py
        dest: "{{ansible_collection_root}}/ciena/{{ product }}/plugins/modules/{{ product }}_{{ item }}.py"
    - name: Creates directory
      file:
        path: "{{ansible_collection_root}}/ciena/{{ product }}/plugins/module_utils/network/{{ product }}/config/{{ item }}"
        state: directory
    - name: Copy config
      ansible.builtin.copy:
        src: build/{{ product }}/plugins/module_utils/network/{{ product }}/config/{{ item }}/{{ item }}.py
        dest: "{{ansible_collection_root}}/ciena/{{ product }}/plugins/module_utils/network/{{ product }}/config/{{ item }}/{{ item }}.py"
    - name: Creates directory
      file:
        path: "{{ansible_collection_root}}/ciena/{{ product }}/plugins/module_utils/network/{{ product }}/argspec/{{ item }}"
        state: directory
    - name: Copy argspec
      ansible.builtin.copy:
        src: build/{{ product }}/plugins/module_utils/network/{{ product }}/argspec/{{ item }}/{{ item }}.py
        dest: "{{ansible_collection_root}}/ciena/{{ product }}/plugins/module_utils/network/{{ product }}/argspec/{{ item }}/{{ item }}.py"
    - name: Creates directory
      file:
        path: "{{ansible_collection_root}}/ciena/{{ product }}/plugins/module_utils/network/{{ product }}/facts/{{ item }}"
        state: directory
    - name: Copy facts gather
      ansible.builtin.copy:
        src: build/{{ product }}/plugins/module_utils/network/{{ product }}/facts/{{ item }}/{{ item }}.py
        dest: "{{ansible_collection_root}}/ciena/{{ product }}/plugins/module_utils/network/{{ product }}/facts/{{ item }}/{{ item }}.py"
    - name: Run black
      ansible.builtin.command: black .
      args:
        chdir: "{{ ansible_collection_root }}/ciena/{{ product }}/plugins"
    # - name: Run doc gen
    #   ansible.builtin.command: collection_prep_add_docs -b master -p .
    #   args:
    #     chdir: "{{ ansible_collection_root }}/ciena/{{ product }}"
