---
- hosts: WS5-1
  gather_facts: false
  connection: ansible.netcommon.netconf
  tasks:
    - name: Generate json spec for classifier yang
      community.yang.generate_spec:
        file: "{{ item }}"
        doctype: config
        json_schema:
          path: "schemas/ws5/{{ item.split('/')[-1]  }}.json"
          defaults: True
      loop: "{{ lookup('fileglob', 'yangs/ws5/*', wantlist=True) }}"
    # - name: Generate json spec for classifier yang
    #   community.yang.generate_spec:
    #     file: yang_files/ciena-openconfig-if-ip.yang
    #     doctype: config
    #     json_schema:
    #       path: "schemas/ciena-openconfig-if-ip.yang.json"
    #       defaults: True
