#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the myos_interfaces module
"""


class InterfacesArgs(object):  # pylint: disable=R0903
    """The arg spec for the myos_interfaces module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
            'options': {'name': {'type': 'str'},
                        'some_bool': {'type': 'bool'},
                        'some_dict': {'options': {'property_01': {'type': 'str'}},
                                      'type': 'dict'},
                        'some_int': {'type': 'int'},
                        'some_string': {'choices': ['choice_a',
                                                    'choice_b',
                                                    'choice_c'],
                                        'default': 'choice_a',
                                        'type': 'str'}},
            'type': 'list'},
 'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
